### PR TITLE
log stack trace in AtmosphereResponse#handleException(Exception)

### PR DESCRIPTION
**Pull request by rgoldberg**

### CODE REVIEW

**Comment by jfarcand** [comment]
@rgoldberg Thanks!

**Comment by rgoldberg** [comment]
Thanks for merging. I hope I put it in the correct branch. I assume it should also somehow get merged into 2.4.x. I doubt it's necessary to back merge into 2.2.x or earlier.

**Comment by rgoldberg** [comment]
I found some more logging issues in atmosphere-rmi-2.3.2.jar.

I know that's a [separate project](https://github.com/Atmosphere/atmosphere-extensions), so I'll create pull requests there.

Should I use branch from extensions-2.3.x, since I'm using 2.3.2, or should I branch from some other branch?

I want to ease your merging into both 2.3.x & 2.4.x.

**Comment by jfarcand** [comment]
Use 2.4 and I will back port.

**Pull request merged**
