### PR TITLE
getInitParameter also from ServletContext

### PR DESCRIPTION
**Pull request by bertung**
If the init parameter does not exists in servlet configuration, also check the servlet context for it.

### CODE REVIEW

**Comment by jfarcand** [comment]
@bertung Make it configurable as it may cause side effect to current application. Make it set to `false` by default. Thanks!!

**Comment by jfarcand** [comment]
Thanks!

**Comment by jfarcand** [comment]
Ouch, this cause major regression
```java
java.lang.NullPointerException
	at org.atmosphere.cpr.AtmosphereFramework.getServletContext(AtmosphereFramework.java:2736)
	at org.atmosphere.cpr.AtmosphereConfig.<init>(AtmosphereConfig.java:55)
	at org.atmosphere.cpr.AtmosphereFramework.newAtmosphereConfig(AtmosphereFramework.java:523)
	at org.atmosphere.cpr.AtmosphereFramework.<init>(AtmosphereFramework.java:516)
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.newAtmosphereFramework(AtmosphereFrameworkInitializer.java:89)
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.newAtmosphereFramework(AtmosphereFrameworkInitializer.java:113)
	at org.atmosphere.cpr.ContainerInitializer.onStartup(ContainerInitializer.java:58)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:106)
	at org.eclipse.jetty.annotations.ServletContainerInitializerListener.doStart(ServletContainerInitializerListener.java:107)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96)
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:115)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:763)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
````

**Comment by bertung** [comment]
Glad that you corrected the regression. I assumed that the servlet context would have been there. Thank you.

**Pull request merged**
