### PR TITLE
HeartbeatInterceptor should respect content of the GET method

### LINKED ISSUE #2325: HeartbeatInterceptor does not work with GET method
`HeartbeatInterceptor` skips the content of the GET method:
https://github.com/Atmosphere/atmosphere/blob/c2e67ed7a8c69ac164af4da58ff7f05b35a6943a/modules/runtime/src/main/java/org/atmosphere/interceptor/HeartbeatInterceptor.java#L197

Because of this, the client's heartbeat message (with 'X' in content) reaches the handler.
At the moment I use workaround with an additional interceptor:
```java
public class HeartbeatWorkaroundInterceptor extends AtmosphereInterceptorAdapter {
    @Override
    public Action inspect(AtmosphereResource r) {
        r.getRequest().method("POST");
        return Action.CONTINUE;
    }

    @Override
    public PRIORITY priority() {
        return InvokationOrder.BEFORE_DEFAULT;
    }
}
```

But I think this is an issue, and `HeartbeatInterceptor` should not take into account the method type. Either I do not understand something...

### PR DESCRIPTION
**Pull request by fenik17**
Fixes #2325.

### CODE REVIEW

**Comment by yadavamit** [comment]
Hi, Do atomosphere supports tomcat 9.x version ?

**Comment by fenik17** [comment]
@yadavamit should support. I did not test. If not working, open an issue, please.

**Comment by yadavamit** [comment]
Thanks for promt response,

Could you please share the link to raise the ticket. I searched but not
able to find the link to log the tickets.

**Comment by yadavamit** [comment]
Forgot to mention that i am using version 2.4.

**Comment by fenik17** [comment]
@yadavamit https://github.com/Atmosphere/atmosphere/issues -> "New issue"

**Comment by yadavamit** [comment]
Thanks alot, i will open a new issue.

**Pull request merged**
