### PR TITLE
Adding unit tests for org.atmosphere.util.uri.UriComponentTest

### PR DESCRIPTION
**Pull request by EdgarScott**
I've analysed your codebase and noticed that `org.atmosphere.util.uri.UriComponent` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

### CODE REVIEW

**Comment by jfarcand** [comment]
@EdgarScott Hi, why have you closed your pull request? I'm happy to integrate your work and interested about more work :-)

**Comment by EdgarScott** [comment]
Hi @jfarcand , just trying to address the build failure. I'll open a new one shortly.

**Comment by EdgarScott** [comment]
Actually, looks like the build error isn't related to the changes that I made. This should build cleanly after issues with atmosphere.runtime.UrlMappingTest are fixed.

**Comment by jfarcand** [comment]
@EdgarScott Let me look

**Comment by jfarcand** [comment]
```[ERROR] 
[ERROR] Please refer to /home/travis/build/Atmosphere/atmosphere/modules/runtime/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] 
[ERROR] Cannot instantiate class org.atmosphere.runtime.UrlMappingTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] 
[ERROR] Cannot instantiate class org.atmosphere.runtime.UrlMappingTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)```

**Pull request closed without merging**
