### PR TITLE
Copy `isSecure()` property from JSR356 `Session`

### PR DESCRIPTION
**Pull request by slovdahl**
Without this, it's impossible to know if a connection is done using SSL or not.

### CODE REVIEW

**Review by jfarcand — APPROVED** [review]

**Comment by slovdahl** [comment]
@jfarcand do you mind if I publish 3.0.9 with this fix?

**Comment by slovdahl** [comment]
Side note, should we switch the default branch to `main` and also remove this line from the README?

> Main development branch is [atmosphere-2.7.x](https://github.com/Atmosphere/atmosphere/tree/atmosphere-2.7.x) Only pull request for that branch will be accepted.

**Comment by jfarcand** [comment]
Perfect approved 😝

**Comment by jfarcand** [comment]
Agree. Do you have the time to do it? I’m on vacation for a couples of
weeks .

**Comment by slovdahl** [comment]
Hmm, I published 3.0.9 built with JDK 8 :grin: It did build without problems. But I now noticed that the README says 3.0.x requires JDK 11. Should I rebuilt it with 11 and publish 3.0.11? :thinking:

**Comment by slovdahl** [comment]
@jfarcand I don't have access to change the default branch. But I have now updated `README.md` in the `main` branch to be up to date, so whenever you have time, please change the default branch for the repository.

**Pull request merged**
