### PR TITLE
github-issue-#2322: AtmosphereResponseImpl#getHeaders should return `…

### PR DESCRIPTION
**Pull request by 0x006EA1E5**
…null` if header not found

This tests and fixes the issue as observed

### CODE REVIEW

**Comment by jfarcand** [comment]
@0x006EA1E5 Gigantic Thanks!

**Comment by 0x006EA1E5** [comment]
You're welcome!  Any idea when 2.4.24 with this change might be available?  It's not urgent for us, but would be great to get this fix in our project and clear our ticket here :)

**Comment by jfarcand** [comment]
@0x006EA1E5 Before the end of the week! I just need some information from @vbarrier on another issue and then I will cut the release.

**Comment by jfarcand** [comment]
Release done! Thanks!

**Pull request merged**
